### ISSUE TITLE
Move to TCS or openc2.org

### ISSUE THREAD

**Issue by sparrell** [dlemire60/other-openc2-work#1]
I think this is great work and really appreciate Dave pulling it together. But I do not think it belongs in a personal repo. I propose it be moved either to the OASIS TSC repo or to github repo that creates https://openc2.org/. Personally I'd vote for openc2.org but either would work for me.

**Comment by dlemire60** [comment]
Done.  

New repo is https://github.com/OpenC2-org/other-openc2-work

Since this isn't really a TC work product, creating an OASIS TCs repo didn't seem like the right way to go, so it's under OpenC2.org.
